services:
  redis:
    image: redis
    container_name: dev-redis
    expose:
      - "6379"
    networks:
    - pickfighter_network

  pickfighter-gateway-service:
    image: pickfighter-service-image
    container_name: pickfighter-gateway-service
    build:
      context: .
      dockerfile: pickfighter/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
    ports:
      - "9091:9091"
    networks:
      - pickfighter_network

  auth-service:
    image: auth-service-image
    container_name: auth-service
    build:
      context: .
      dockerfile: auth/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
      - DB_URL=postgres://postgres:greedisgood@172.17.0.1:5432/pickfighter_db
    expose:
      - "9092"
    networks:
      - pickfighter_network
    

  fighters-service:
    image: fighters-service-image
    container_name: fighters-service
    build:
      context: .
      dockerfile: fighters/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
      - DB_URL=postgres://postgres:greedisgood@172.17.0.1:5432/pickfighter_db
    expose:
      - "9093"
    networks:
      - pickfighter_network

  events-service:
    image: events-service-image
    container_name: events-service
    build:
      context: .
      dockerfile: events/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
      - DB_URL=postgres://postgres:greedisgood@172.17.0.1:5432/pickfighter_db
    expose:
      - "9094"
    networks:
      - pickfighter_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:8081"
    depends_on:
      - pickfighter-gateway-service
    networks:
      - pickfighter_network

networks:
  pickfighter_network:
    name: pickfighter_network
    driver: bridge