// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/pgxs/pgx.go
//
// Generated by this command:
//
//	mockgen -source=pkg/pgxs/pgx.go -destination=pkg/pgxs/mocks/mock_pgx.go
//

// Package mock_pgxs is a generated GoMock package.
package mock_pgxs

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	gomock "go.uber.org/mock/gomock"
)

// MockPickfighterRepo is a mock of PickfighterRepo interface.
type MockPickfighterRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPickfighterRepoMockRecorder
}

// MockPickfighterRepoMockRecorder is the mock recorder for MockPickfighterRepo.
type MockPickfighterRepoMockRecorder struct {
	mock *MockPickfighterRepo
}

// NewMockPickfighterRepo creates a new mock instance.
func NewMockPickfighterRepo(ctrl *gomock.Controller) *MockPickfighterRepo {
	mock := &MockPickfighterRepo{ctrl: ctrl}
	mock.recorder = &MockPickfighterRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPickfighterRepo) EXPECT() *MockPickfighterRepoMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockPickfighterRepo) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockPickfighterRepoMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockPickfighterRepo)(nil).BeginTx), ctx, txOptions)
}

// ConnectDBPool mocks base method.
func (m *MockPickfighterRepo) ConnectDBPool(ctx context.Context) (*pgxpool.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectDBPool", ctx)
	ret0, _ := ret[0].(*pgxpool.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectDBPool indicates an expected call of ConnectDBPool.
func (mr *MockPickfighterRepoMockRecorder) ConnectDBPool(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectDBPool", reflect.TypeOf((*MockPickfighterRepo)(nil).ConnectDBPool), ctx)
}

// DebugLogSqlErr mocks base method.
func (m *MockPickfighterRepo) DebugLogSqlErr(q string, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebugLogSqlErr", q, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// DebugLogSqlErr indicates an expected call of DebugLogSqlErr.
func (mr *MockPickfighterRepoMockRecorder) DebugLogSqlErr(q, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugLogSqlErr", reflect.TypeOf((*MockPickfighterRepo)(nil).DebugLogSqlErr), q, err)
}

// DeleteRecords mocks base method.
func (m *MockPickfighterRepo) DeleteRecords(ctx context.Context, scheme, tableName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecords", ctx, scheme, tableName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecords indicates an expected call of DeleteRecords.
func (mr *MockPickfighterRepoMockRecorder) DeleteRecords(ctx, scheme, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecords", reflect.TypeOf((*MockPickfighterRepo)(nil).DeleteRecords), ctx, scheme, tableName)
}

// GetPool mocks base method.
func (m *MockPickfighterRepo) GetPool() *pgxpool.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPool")
	ret0, _ := ret[0].(*pgxpool.Pool)
	return ret0
}

// GetPool indicates an expected call of GetPool.
func (mr *MockPickfighterRepoMockRecorder) GetPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPool", reflect.TypeOf((*MockPickfighterRepo)(nil).GetPool))
}

// GetPoolConfig mocks base method.
func (m *MockPickfighterRepo) GetPoolConfig() (*pgxpool.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoolConfig")
	ret0, _ := ret[0].(*pgxpool.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoolConfig indicates an expected call of GetPoolConfig.
func (mr *MockPickfighterRepoMockRecorder) GetPoolConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoolConfig", reflect.TypeOf((*MockPickfighterRepo)(nil).GetPoolConfig))
}

// GracefulShutdown mocks base method.
func (m *MockPickfighterRepo) GracefulShutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulShutdown")
}

// GracefulShutdown indicates an expected call of GracefulShutdown.
func (mr *MockPickfighterRepoMockRecorder) GracefulShutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulShutdown", reflect.TypeOf((*MockPickfighterRepo)(nil).GracefulShutdown))
}

// SanitizeString mocks base method.
func (m *MockPickfighterRepo) SanitizeString(s string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SanitizeString", s)
	ret0, _ := ret[0].(string)
	return ret0
}

// SanitizeString indicates an expected call of SanitizeString.
func (mr *MockPickfighterRepoMockRecorder) SanitizeString(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeString", reflect.TypeOf((*MockPickfighterRepo)(nil).SanitizeString), s)
}
