package model

import (
	"testing"

	"pickfighter.com/gen"
	"github.com/stretchr/testify/assert"
)

func TestFighterString(t *testing.T) {
	testCases := []struct {
		input    Division
		expected string
	}{
		{Flyweight, "Flyweight"},
		{Bantamweight, "Bantamweight"},
		{Featherweight, "Featherweight"},
		{Lightweight, "Lightweight"},
		{Welterweight, "Welterweight"},
		{Middleweight, "Middleweight"},
		{Lightheavyweight, "Light Heavyweight"},
		{Heavyweight, "Heavyweight"},
		{WomensStrawweight, "Women's Strawweight"},
		{WomensFlyweight, "Women's Flyweight"},
		{WomensBantamweight, "Women's Bantamweight"},
		{WomensFeatherweight, "Women's Featherweight"},
	}

	for _, testCase := range testCases {
		result := testCase.input.String()

		if result != testCase.expected {
			t.Errorf("For input %v, expected %s, but got %s", testCase.input, testCase.expected, result)
		}
	}
}

func TestFighterToProto(t *testing.T) {
	tests := []struct {
		name     string
		input    *Fighter
		expected *gen.Fighter
	}{
		{
			name: "Basic Test",
			input: &Fighter{
				FighterId:      1,
				Name:           "John Doe",
				NickName:       "The Champ",
				Division:       Division(Lightweight),
				Status:         "Active",
				Hometown:       "New York",
				TrainsAt:       "NY Gym",
				FightingStyle:  "Boxing",
				Age:            30,
				Height:         180.0,
				Weight:         75.0,
				OctagonDebut:   "2021-01-01",
				DebutTimestamp: 1610123456,
				Reach:          72.0,
				LegReach:       40.0,
				Wins:           10,
				Loses:          2,
				Draw:           1,
				FighterUrl:     "http://example.com/fighter1",
				ImageUrl:       "http://example.com/fighter1.jpg",
				Stats: FighterStats{
					StatId:               101,
					FighterId:            1,
					TotalSigStrLanded:    100,
					TotalSigStrAttempted: 150,
					StrAccuracy:          67,
					TotalTkdLanded:       20,
					TotalTkdAttempted:    30,
					TkdAccuracy:          67,
					SigStrLanded:         5.5,
					SigStrAbs:            2.5,
					SigStrDefense:        4,
					TakedownDefense:      3,
					TakedownAvg:          1.5,
					SubmissionAvg:        0.5,
					KnockdownAvg:         0.8,
					AvgFightTime:         "10m",
					WinByKO:              5,
					WinBySub:             2,
					WinByDec:             3,
				},
			},
			expected: &gen.Fighter{
				FighterId:      1,
				Name:           "John Doe",
				NickName:       "The Champ",
				Division:       3,
				Status:         "Active",
				Hometown:       "New York",
				TrainsAt:       "NY Gym",
				FightingStyle:  "Boxing",
				Age:            30,
				Height:         180.0,
				Weight:         75.0,
				OctagonDebut:   "2021-01-01",
				DebutTimestamp: 1610123456,
				Reach:          72.0,
				LegReach:       40.0,
				Wins:           10,
				Loses:          2,
				Draw:           1,
				FighterUrl:     "http://example.com/fighter1",
				ImageUrl:       "http://example.com/fighter1.jpg",
				Stats: &gen.FighterStats{
					StatId:               101,
					FighterId:            1,
					TotalSigStrLanded:    100,
					TotalSigStrAttempted: 150,
					StrAccuracy:          67,
					TotalTkdLanded:       20,
					TotalTkdAttempted:    30,
					TkdAccuracy:          67,
					SigStrLanded:         5.5,
					SigStrAbs:            2.5,
					SigStrDefense:        4,
					TakedownDefense:      3,
					TakedownAvg:          1.5,
					SubmissionAvg:        0.5,
					KnockdownAvg:         0.8,
					AvgFightTime:         "10m",
					WinByKO:              5,
					WinBySub:             2,
					WinByDec:             3,
				},
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			actual := FighterToProto(tc.input)
			assert.Equal(t, tc.expected, actual)
		})
	}
}

func TestFightersToProto(t *testing.T) {
	tests := []struct {
		name     string
		input    []*Fighter
		expected []*gen.Fighter
	}{
		{
			name:     "Empty List",
			input:    []*Fighter{},
			expected: []*gen.Fighter{},
		},
		{
			name: "Single Fighter",
			input: []*Fighter{
				{
					FighterId:      1,
					Name:           "John Doe",
					NickName:       "The Champ",
					Division:       Division(Lightweight),
					Status:         "Active",
					Hometown:       "New York",
					TrainsAt:       "NY Gym",
					FightingStyle:  "Boxing",
					Age:            30,
					Height:         180.0,
					Weight:         75.0,
					OctagonDebut:   "2021-01-01",
					DebutTimestamp: 1610123456,
					Reach:          72.0,
					LegReach:       40.0,
					Wins:           10,
					Loses:          2,
					Draw:           1,
					FighterUrl:     "http://example.com/fighter1",
					ImageUrl:       "http://example.com/fighter1.jpg",
					Stats: FighterStats{
						StatId:               101,
						FighterId:            1,
						TotalSigStrLanded:    100,
						TotalSigStrAttempted: 150,
						StrAccuracy:          67,
						TotalTkdLanded:       20,
						TotalTkdAttempted:    30,
						TkdAccuracy:          67,
						SigStrLanded:         5.5,
						SigStrAbs:            2.5,
						SigStrDefense:        4,
						TakedownDefense:      3,
						TakedownAvg:          1.5,
						SubmissionAvg:        0.5,
						KnockdownAvg:         0.8,
						AvgFightTime:         "10m",
						WinByKO:              5,
						WinBySub:             2,
						WinByDec:             3,
					},
				},
			},
			expected: []*gen.Fighter{
				{
					FighterId:      1,
					Name:           "John Doe",
					NickName:       "The Champ",
					Division:       3,
					Status:         "Active",
					Hometown:       "New York",
					TrainsAt:       "NY Gym",
					FightingStyle:  "Boxing",
					Age:            30,
					Height:         180.0,
					Weight:         75.0,
					OctagonDebut:   "2021-01-01",
					DebutTimestamp: 1610123456,
					Reach:          72.0,
					LegReach:       40.0,
					Wins:           10,
					Loses:          2,
					Draw:           1,
					FighterUrl:     "http://example.com/fighter1",
					ImageUrl:       "http://example.com/fighter1.jpg",
					Stats: &gen.FighterStats{
						StatId:               101,
						FighterId:            1,
						TotalSigStrLanded:    100,
						TotalSigStrAttempted: 150,
						StrAccuracy:          67,
						TotalTkdLanded:       20,
						TotalTkdAttempted:    30,
						TkdAccuracy:          67,
						SigStrLanded:         5.5,
						SigStrAbs:            2.5,
						SigStrDefense:        4,
						TakedownDefense:      3,
						TakedownAvg:          1.5,
						SubmissionAvg:        0.5,
						KnockdownAvg:         0.8,
						AvgFightTime:         "10m",
						WinByKO:              5,
						WinBySub:             2,
						WinByDec:             3,
					},
				},
			},
		},
		{
			name: "Multiple Fighters",
			input: []*Fighter{
				{
					FighterId:      1,
					Name:           "John Doe",
					NickName:       "The Champ",
					Division:       Division(Lightweight),
					Status:         "Active",
					Hometown:       "New York",
					TrainsAt:       "NY Gym",
					FightingStyle:  "Boxing",
					Age:            30,
					Height:         180.0,
					Weight:         75.0,
					OctagonDebut:   "2021-01-01",
					DebutTimestamp: 1610123456,
					Reach:          72.0,
					LegReach:       40.0,
					Wins:           10,
					Loses:          2,
					Draw:           1,
					FighterUrl:     "http://example.com/fighter1",
					ImageUrl:       "http://example.com/fighter1.jpg",
					Stats: FighterStats{
						StatId:               101,
						FighterId:            1,
						TotalSigStrLanded:    100,
						TotalSigStrAttempted: 150,
						StrAccuracy:          67,
						TotalTkdLanded:       20,
						TotalTkdAttempted:    30,
						TkdAccuracy:          67,
						SigStrLanded:         5.5,
						SigStrAbs:            2.5,
						SigStrDefense:        4,
						TakedownDefense:      3,
						TakedownAvg:          1.5,
						SubmissionAvg:        0.5,
						KnockdownAvg:         0.8,
						AvgFightTime:         "10m",
						WinByKO:              5,
						WinBySub:             2,
						WinByDec:             3,
					},
				},
				{
					FighterId:      2,
					Name:           "Jane Smith",
					NickName:       "The Queen",
					Division:       Division(Flyweight),
					Status:         "Inactive",
					Hometown:       "Los Angeles",
					TrainsAt:       "LA Gym",
					FightingStyle:  "Jiu-Jitsu",
					Age:            28,
					Height:         165.0,
					Weight:         55.0,
					OctagonDebut:   "2020-05-01",
					DebutTimestamp: 1588323456,
					Reach:          68.0,
					LegReach:       35.0,
					Wins:           12,
					Loses:          4,
					Draw:           0,
					FighterUrl:     "http://example.com/fighter2",
					ImageUrl:       "http://example.com/fighter2.jpg",
					Stats: FighterStats{
						StatId:               102,
						FighterId:            2,
						TotalSigStrLanded:    120,
						TotalSigStrAttempted: 180,
						StrAccuracy:          66,
						TotalTkdLanded:       25,
						TotalTkdAttempted:    35,
						TkdAccuracy:          71,
						SigStrLanded:         6.0,
						SigStrAbs:            3.0,
						SigStrDefense:        5,
						TakedownDefense:      4,
						TakedownAvg:          1.8,
						SubmissionAvg:        1.0,
						KnockdownAvg:         0.9,
						AvgFightTime:         "12m",
						WinByKO:              6,
						WinBySub:             4,
						WinByDec:             2,
					},
				},
			},
			expected: []*gen.Fighter{
				{
					FighterId:      1,
					Name:           "John Doe",
					NickName:       "The Champ",
					Division:       3,
					Status:         "Active",
					Hometown:       "New York",
					TrainsAt:       "NY Gym",
					FightingStyle:  "Boxing",
					Age:            30,
					Height:         180.0,
					Weight:         75.0,
					OctagonDebut:   "2021-01-01",
					DebutTimestamp: 1610123456,
					Reach:          72.0,
					LegReach:       40.0,
					Wins:           10,
					Loses:          2,
					Draw:           1,
					FighterUrl:     "http://example.com/fighter1",
					ImageUrl:       "http://example.com/fighter1.jpg",
					Stats: &gen.FighterStats{
						StatId:               101,
						FighterId:            1,
						TotalSigStrLanded:    100,
						TotalSigStrAttempted: 150,
						StrAccuracy:          67,
						TotalTkdLanded:       20,
						TotalTkdAttempted:    30,
						TkdAccuracy:          67,
						SigStrLanded:         5.5,
						SigStrAbs:            2.5,
						SigStrDefense:        4,
						TakedownDefense:      3,
						TakedownAvg:          1.5,
						SubmissionAvg:        0.5,
						KnockdownAvg:         0.8,
						AvgFightTime:         "10m",
						WinByKO:              5,
						WinBySub:             2,
						WinByDec:             3,
					},
				},
				{
					FighterId:      2,
					Name:           "Jane Smith",
					NickName:       "The Queen",
					Division:       0,
					Status:         "Inactive",
					Hometown:       "Los Angeles",
					TrainsAt:       "LA Gym",
					FightingStyle:  "Jiu-Jitsu",
					Age:            28,
					Height:         165.0,
					Weight:         55.0,
					OctagonDebut:   "2020-05-01",
					DebutTimestamp: 1588323456,
					Reach:          68.0,
					LegReach:       35.0,
					Wins:           12,
					Loses:          4,
					Draw:           0,
					FighterUrl:     "http://example.com/fighter2",
					ImageUrl:       "http://example.com/fighter2.jpg",
					Stats: &gen.FighterStats{
						StatId:               102,
						FighterId:            2,
						TotalSigStrLanded:    120,
						TotalSigStrAttempted: 180,
						StrAccuracy:          66,
						TotalTkdLanded:       25,
						TotalTkdAttempted:    35,
						TkdAccuracy:          71,
						SigStrLanded:         6.0,
						SigStrAbs:            3.0,
						SigStrDefense:        5,
						TakedownDefense:      4,
						TakedownAvg:          1.8,
						SubmissionAvg:        1.0,
						KnockdownAvg:         0.9,
						AvgFightTime:         "12m",
						WinByKO:              6,
						WinBySub:             4,
						WinByDec:             2,
					},
				},
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			actual := FightersToProto(tc.input)
			assert.Equal(t, tc.expected, actual)
		})
	}
}

func TestFighterFromProto(t *testing.T) {
	tests := []struct {
		name     string
		input    *gen.Fighter
		expected *Fighter
	}{
		{
			name: "Basic Fighter",
			input: &gen.Fighter{
				FighterId:      1,
				Name:           "John Doe",
				NickName:       "The Champ",
				Division:       3,
				Status:         "Active",
				Hometown:       "New York",
				TrainsAt:       "NY Gym",
				FightingStyle:  "Boxing",
				Age:            30,
				OctagonDebut:   "2021-01-01",
				DebutTimestamp: 1610123456,
				Reach:          72.0,
				LegReach:       40.0,
				Wins:           10,
				Loses:          2,
				Draw:           1,
				FighterUrl:     "http://example.com/fighter1",
				ImageUrl:       "http://example.com/fighter1.jpg",
				Stats: &gen.FighterStats{
					StatId:               101,
					FighterId:            1,
					TotalSigStrLanded:    100,
					TotalSigStrAttempted: 150,
					StrAccuracy:          67,
					TotalTkdLanded:       20,
					TotalTkdAttempted:    30,
					TkdAccuracy:          67,
					SigStrLanded:         5.5,
					SigStrAbs:            2.5,
					SigStrDefense:        4,
					TakedownDefense:      3,
					TakedownAvg:          1.5,
					SubmissionAvg:        0.5,
					KnockdownAvg:         0.8,
					AvgFightTime:         "10m",
					WinByKO:              5,
					WinBySub:             2,
					WinByDec:             3,
				},
			},
			expected: &Fighter{
				FighterId:      1,
				Name:           "John Doe",
				NickName:       "The Champ",
				Division:       Division(3),
				Status:         FighterStatus("Active"),
				Hometown:       "New York",
				TrainsAt:       "NY Gym",
				FightingStyle:  "Boxing",
				Age:            int8(30),
				OctagonDebut:   "2021-01-01",
				DebutTimestamp: int(1610123456),
				Reach:          72.0,
				LegReach:       40.0,
				Wins:           int(10),
				Loses:          int(2),
				Draw:           int(1),
				FighterUrl:     "http://example.com/fighter1",
				ImageUrl:       "http://example.com/fighter1.jpg",
				Stats: FighterStats{
					StatId:               101,
					FighterId:            1,
					TotalSigStrLanded:    100,
					TotalSigStrAttempted: 150,
					StrAccuracy:          67,
					TotalTkdLanded:       20,
					TotalTkdAttempted:    30,
					TkdAccuracy:          67,
					SigStrLanded:         5.5,
					SigStrAbs:            2.5,
					SigStrDefense:        4,
					TakedownDefense:      3,
					TakedownAvg:          1.5,
					SubmissionAvg:        0.5,
					KnockdownAvg:         0.8,
					AvgFightTime:         "10m",
					WinByKO:              5,
					WinBySub:             2,
					WinByDec:             3,
				},
			},
		},
		{
			name: "Another Fighter",
			input: &gen.Fighter{
				FighterId:      2,
				Name:           "Jane Smith",
				NickName:       "The Queen",
				Division:       0,
				Status:         "Inactive",
				Hometown:       "Los Angeles",
				TrainsAt:       "LA Gym",
				FightingStyle:  "Jiu-Jitsu",
				Age:            28,
				OctagonDebut:   "2020-05-01",
				DebutTimestamp: 1588323456,
				Reach:          68.0,
				LegReach:       35.0,
				Wins:           12,
				Loses:          4,
				Draw:           0,
				FighterUrl:     "http://example.com/fighter2",
				ImageUrl:       "http://example.com/fighter2.jpg",
				Stats: &gen.FighterStats{
					StatId:               102,
					FighterId:            2,
					TotalSigStrLanded:    120,
					TotalSigStrAttempted: 180,
					StrAccuracy:          66,
					TotalTkdLanded:       25,
					TotalTkdAttempted:    35,
					TkdAccuracy:          71,
					SigStrLanded:         6.0,
					SigStrAbs:            3.0,
					SigStrDefense:        5,
					TakedownDefense:      4,
					TakedownAvg:          1.8,
					SubmissionAvg:        1.0,
					KnockdownAvg:         0.9,
					AvgFightTime:         "12m",
					WinByKO:              6,
					WinBySub:             4,
					WinByDec:             2,
				},
			},
			expected: &Fighter{
				FighterId:      2,
				Name:           "Jane Smith",
				NickName:       "The Queen",
				Division:       Division(0),
				Status:         FighterStatus("Inactive"),
				Hometown:       "Los Angeles",
				TrainsAt:       "LA Gym",
				FightingStyle:  "Jiu-Jitsu",
				Age:            int8(28),
				OctagonDebut:   "2020-05-01",
				DebutTimestamp: int(1588323456),
				Reach:          68.0,
				LegReach:       35.0,
				Wins:           int(12),
				Loses:          int(4),
				Draw:           int(0),
				FighterUrl:     "http://example.com/fighter2",
				ImageUrl:       "http://example.com/fighter2.jpg",
				Stats: FighterStats{
					StatId:               102,
					FighterId:            2,
					TotalSigStrLanded:    120,
					TotalSigStrAttempted: 180,
					StrAccuracy:          66,
					TotalTkdLanded:       25,
					TotalTkdAttempted:    35,
					TkdAccuracy:          71,
					SigStrLanded:         6.0,
					SigStrAbs:            3.0,
					SigStrDefense:        5,
					TakedownDefense:      4,
					TakedownAvg:          1.8,
					SubmissionAvg:        1.0,
					KnockdownAvg:         0.9,
					AvgFightTime:         "12m",
					WinByKO:              6,
					WinBySub:             4,
					WinByDec:             2,
				},
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			actual := FighterFromProto(tc.input)
			assert.Equal(t, tc.expected, actual)
		})
	}
}

func TestFightersFromProto(t *testing.T) {
	tests := []struct {
		name     string
		input    []*gen.Fighter
		expected []*Fighter
	}{
		{
			name: "Basic Fighters",
			input: []*gen.Fighter{
				{
					FighterId:      1,
					Name:           "John Doe",
					NickName:       "The Champ",
					Division:       0,
					Status:         "Active",
					Hometown:       "New York",
					TrainsAt:       "NY Gym",
					FightingStyle:  "Boxing",
					Age:            30,
					OctagonDebut:   "2021-01-01",
					DebutTimestamp: 1610123456,
					Reach:          72.0,
					LegReach:       40.0,
					Wins:           10,
					Loses:          2,
					Draw:           1,
					FighterUrl:     "http://example.com/fighter1",
					ImageUrl:       "http://example.com/fighter1.jpg",
					Stats: &gen.FighterStats{
						StatId:               101,
						FighterId:            1,
						TotalSigStrLanded:    100,
						TotalSigStrAttempted: 150,
						StrAccuracy:          67,
						TotalTkdLanded:       20,
						TotalTkdAttempted:    30,
						TkdAccuracy:          67,
						SigStrLanded:         5.5,
						SigStrAbs:            2.5,
						SigStrDefense:        4,
						TakedownDefense:      3,
						TakedownAvg:          1.5,
						SubmissionAvg:        0.5,
						KnockdownAvg:         0.8,
						AvgFightTime:         "10m",
						WinByKO:              5,
						WinBySub:             2,
						WinByDec:             3,
					},
				},
				{
					FighterId:      2,
					Name:           "Jane Smith",
					NickName:       "The Queen",
					Division:       3,
					Status:         "Inactive",
					Hometown:       "Los Angeles",
					TrainsAt:       "LA Gym",
					FightingStyle:  "Jiu-Jitsu",
					Age:            28,
					OctagonDebut:   "2020-05-01",
					DebutTimestamp: 1588323456,
					Reach:          68.0,
					LegReach:       35.0,
					Wins:           12,
					Loses:          4,
					Draw:           0,
					FighterUrl:     "http://example.com/fighter2",
					ImageUrl:       "http://example.com/fighter2.jpg",
					Stats: &gen.FighterStats{
						StatId:               102,
						FighterId:            2,
						TotalSigStrLanded:    120,
						TotalSigStrAttempted: 180,
						StrAccuracy:          66,
						TotalTkdLanded:       25,
						TotalTkdAttempted:    35,
						TkdAccuracy:          71,
						SigStrLanded:         6.0,
						SigStrAbs:            3.0,
						SigStrDefense:        5,
						TakedownDefense:      4,
						TakedownAvg:          1.8,
						SubmissionAvg:        1.0,
						KnockdownAvg:         0.9,
						AvgFightTime:         "12m",
						WinByKO:              6,
						WinBySub:             4,
						WinByDec:             2,
					},
				},
			},
			expected: []*Fighter{
				{
					FighterId:      1,
					Name:           "John Doe",
					NickName:       "The Champ",
					Division:       Division(0),
					Status:         FighterStatus("Active"),
					Hometown:       "New York",
					TrainsAt:       "NY Gym",
					FightingStyle:  "Boxing",
					Age:            int8(30),
					OctagonDebut:   "2021-01-01",
					DebutTimestamp: int(1610123456),
					Reach:          72.0,
					LegReach:       40.0,
					Wins:           int(10),
					Loses:          int(2),
					Draw:           int(1),
					FighterUrl:     "http://example.com/fighter1",
					ImageUrl:       "http://example.com/fighter1.jpg",
					Stats: FighterStats{
						StatId:               101,
						FighterId:            1,
						TotalSigStrLanded:    100,
						TotalSigStrAttempted: 150,
						StrAccuracy:          67,
						TotalTkdLanded:       20,
						TotalTkdAttempted:    30,
						TkdAccuracy:          67,
						SigStrLanded:         5.5,
						SigStrAbs:            2.5,
						SigStrDefense:        4,
						TakedownDefense:      3,
						TakedownAvg:          1.5,
						SubmissionAvg:        0.5,
						KnockdownAvg:         0.8,
						AvgFightTime:         "10m",
						WinByKO:              5,
						WinBySub:             2,
						WinByDec:             3,
					},
				},
				{
					FighterId:      2,
					Name:           "Jane Smith",
					NickName:       "The Queen",
					Division:       Division(3), // предполагаем, что 2 сопоставляется с "Flyweight"
					Status:         FighterStatus("Inactive"),
					Hometown:       "Los Angeles",
					TrainsAt:       "LA Gym",
					FightingStyle:  "Jiu-Jitsu",
					Age:            int8(28),
					OctagonDebut:   "2020-05-01",
					DebutTimestamp: int(1588323456),
					Reach:          68.0,
					LegReach:       35.0,
					Wins:           int(12),
					Loses:          int(4),
					Draw:           int(0),
					FighterUrl:     "http://example.com/fighter2",
					ImageUrl:       "http://example.com/fighter2.jpg",
					Stats: FighterStats{
						StatId:               102,
						FighterId:            2,
						TotalSigStrLanded:    120,
						TotalSigStrAttempted: 180,
						StrAccuracy:          66,
						TotalTkdLanded:       25,
						TotalTkdAttempted:    35,
						TkdAccuracy:          71,
						SigStrLanded:         6.0,
						SigStrAbs:            3.0,
						SigStrDefense:        5,
						TakedownDefense:      4,
						TakedownAvg:          1.8,
						SubmissionAvg:        1.0,
						KnockdownAvg:         0.9,
						AvgFightTime:         "12m",
						WinByKO:              6,
						WinBySub:             4,
						WinByDec:             2,
					},
				},
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			actual := FightersFromProto(tc.input)
			assert.Equal(t, tc.expected, actual)
		})
	}
}

func TestFightersReqToProto(t *testing.T) {
	tests := []struct {
		name     string
		input    FightersRequest
		expected *gen.FightersRequest
	}{
		{
			name: "Basic Case with FightersIds",
			input: FightersRequest{
				Status:      "Active",
				FightersIds: []int32{1, 2, 3},
			},
			expected: &gen.FightersRequest{
				Status:      "Active",
				FightersIds: []int32{1, 2, 3},
			},
		},
		{
			name: "Case with Empty FightersIds",
			input: FightersRequest{
				Status:      "Inactive",
				FightersIds: nil,
			},
			expected: &gen.FightersRequest{
				Status: "Inactive",
			},
		},
		{
			name: "Case with Empty Status",
			input: FightersRequest{
				Status:      "",
				FightersIds: []int32{10, 20},
			},
			expected: &gen.FightersRequest{
				Status:      "",
				FightersIds: []int32{10, 20},
			},
		},
		{
			name: "Case with Empty Status and Empty FightersIds",
			input: FightersRequest{
				Status:      "",
				FightersIds: nil,
			},
			expected: &gen.FightersRequest{
				Status: "",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			actual := FightersReqToProto(tc.input)
			assert.Equal(t, tc.expected, actual)
		})
	}
}
