events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    upstream gateway {
        server pickfighter-gateway-service:9091;
    }

    server {
        listen 80;
        server_name api.pickfighter.com;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name api.pickfighter.com;

        ssl_certificate /etc/letsencrypt/live/api.pickfighter.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.pickfighter.com/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://gateway;
        }

        location /api/auth/ {
            proxy_pass http://gateway;
            rewrite ^/api/auth/(.*)$ /$1 break;
        }

        location /api/events/ {
            proxy_pass http://gateway;
            rewrite ^/api/events/(.*)$ /$1 break;
        }

        location /api/fighters/ {
            proxy_pass http://gateway;
            rewrite ^/api/fighters/(.*)$ /$1 break;
        }

        location /api/health {
    		proxy_pass http://gateway/health;
        }
    }
}